name: graduation_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  cached_network_image: ^3.2.0
  lottie:
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  url_launcher: ^6.0.10
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.0
  readmore: ^2.1.0
  badges: ^2.0.2
  barcode_widget: ^2.0.2
  introduction_screen: ^3.0.2
  location:
  provider:
  uuid: ^3.0.6
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  google_sign_in: ^5.3.3
  cloud_firestore: ^3.1.9
  firebase_storage: ^10.2.8
  firebase_database: ^9.0.7
  sound_stream: ^0.3.0
  dialogflow_grpc: ^0.2.9
  rxdart: ^0.27.1
  flutter_credit_card: ^2.0.0
  card_scanner: ^1.0.1-prerelease



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/Shtably-logo.png"
  flutter_lints: ^1.0.0
dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_database_platform_interface: 0.2.0+5


flutter:

  uses-material-design: true

  assets:
    #- assets/logo.png
    - assets/image/onboarding/
    - assets/image/
    - assets/image/login.json
    - assets/image/spalsh.json
    - assets/dialogflow/shtably-graditionproject-jeai-143a375c58fd.json



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

